### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by osekeranen** [puuro-maria/ot-harjoitustyo#1]
Projekti kloonattu GitHubista 28.4. klo 17.43

## Luokkarakenne ja pakkaukset
* Ohjelman toiminnallisuus on jaoteltu hyvin omiin pakkauksiinsa, joista jokainen ajaa omaa asiaansa (ui, logic, domain, dao)
* Luokat noudattavat single responsibility -periaatetta

## UI
* TextUin konstruktori vaatii Scanner-olion, vaikka määrittelet kyseisessä luokassa jo skannerin
  * poistaisin konstruktorin parametreistä skannerin ja samalla turhaksi jääneen skannerin luomisen Main-luokasta
* Käytät TextUi-luokassa kahta skanneria sc ja scint. Voisit käyttää skanneria sc kaikkeen mihin käytät skanneria scint ja poistaa scintin
 * Rekisteröitymisessä tarkistat että tietyn opiskelijanumeron omaava opiskelija ei ole jo rekisteröitynyt, hyvä niin. Virheilmoitus tulee kuitenkin vasta kun olet myös syöttänyt salasanan ja yliopiston. Pystyisitkö tarkistamaan heti opiskelijanumeron ilmoittamisen jälkeen onko numero jo tietokannassa ja antaa virheilmoituksen jo silloin
* TextUi-luokassa salasanoja kirjoittaessa käyttäjän kirjoittama salasana näkyy komentorivillä. Pystyisitkö maskeerata salasanan esimerkiksi Javan [Console](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/Console.html)-luokan `readPassword()`-metodin avulla

## Domain
* Koska Course-luokan id-muuttuja vaikuttaisi olevan vain käyttäjää varten, esimerkiksi yliopistojen kurssien identifioimista varten vaihtaisin sen intistä Stringiksi, sillä esimerkiksi Helsingin yliopisto käyttää kurssien tunnistamiseen kirjaimista ja numeroista koostuvaa sarjaa (esimerkiksi ohjelmistotekniikan tunniste on TKT20002)
* Sisäänkirjautuminen ei anna virheilmoitusta mikäli tietokanta tyhjä. Virhe johtuu ilmeisesti siitä, että opiskelijat tallentava HashMap `transcript` alustetaan vasta ensimmäistä oppilasta lisätessä
  * Voisiko TranscriptOfRecordsille esimerkiksi tehdä konstruktorin ja HashMapin siellä? Tai lisätä ohjelman suorituksen alussa sinne esimerkkioppilaan (vaikkapa Mikko Mallikas, opiskelijanumero 123456789, jne.) ja alustaa sen siten?

**Comment by puuro-maria** [comment]
TranscriptOfRecords-luokka poistettu kokonaan ja toteutettu toisella tavalla (kurssilla on attribuuttina opiskelijanumero, eikä nyt olekaan monesta moneen -suhdetta opiskelijan ja kurssin välillä). Nyt käytössä myös graafinen UI ja tekstikäyttöliittymä poistettu. Kurssi-id:stä todella hyvä pointti. Kiitos kommenteista. 👍
